# Generated by Django 5.0.3 on 2024-03-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_remove_model_dataset_remove_model_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='architecture',
        ),
        migrations.AddField(
            model_name='model',
            name='formatted_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='model',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
