# Generated by Django 5.0.3 on 2024-03-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='model_type',
        ),
    ]
