# Generated by Django 5.0.3 on 2024-03-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_remove_experiment_project_remove_experiment_dataset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='parameters',
        ),
    ]
