# Generated by Django 5.0.3 on 2024-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_remove_model_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='domain',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
