databases:
  - name: Hivemind
    plan: free
    databaseName: hivemind_user
    user: hivemind_user

services:
  - type: web
    plan: free
    name: Hivetrain
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Hivemind
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
